[package]
name = "todo"
version = "0.1.0"
authors = ["Luke Ryan <luke.ryan@xero.com>"]

[dependencies]
clap = "2.31.2"
serde = "1.0.41"
serde_json = "1.0"
postgres = "0.15.2"
rocket = "0.3.11"
rocket_codegen = "0.3.11"
serde_derive = "1.0.60"
rocket_contrib = "0.3.11"